# Autogenerated wrapper script for lwbgt_jll for aarch64-apple-darwin
export liblwbgt

JLLWrappers.@generate_wrapper_header("lwbgt")
JLLWrappers.@declare_library_product(liblwbgt, "@rpath/liblwbgt.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblwbgt,
        "lib/liblwbgt.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
