# Autogenerated wrapper script for lwbgt_jll for x86_64-w64-mingw32
export liblwbgt

JLLWrappers.@generate_wrapper_header("lwbgt")
JLLWrappers.@declare_library_product(liblwbgt, "lwbgt.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblwbgt,
        "bin\\lwbgt.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
